### PR TITLE
build binder-link.yml

### PR DESCRIPTION
**Pull request by AnirudhVIyer**
## Describe your changes
Added a workflow to comment the binder link on the comments section of a PR
## Issue number

Closes #1107

## Checklist before requesting a review

- [x] Performed a self-review of my code
- [x] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [x] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [x] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

----
:books: Documentation preview :books:: https://jupysql--571.org.readthedocs.build/en/571/

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204699387681445

### CODE REVIEW

**Comment by AnirudhVIyer** [comment]
@edublancas can you please label this PR as `allow-workflow-edits`. I don't think I can do it from my end.

**Comment by edublancas** [comment]
just did, please push a new commit:  `git commit --allow-empty -m ci`

**Comment by edublancas** [comment]
this was opened in the wrong repository. the issue must be opened in the ploomber/ploomber repo. https://github.com/ploomber/ploomber/issues/1107

**Comment by edublancas** [comment]
please re-open it there and let me know once it's ready for review

**Comment by AnirudhVIyer** [comment]
Got it! Making the changes

**Pull request closed without merging**
