### PR TITLE
Telemetry

### PR DESCRIPTION
**Pull request by yafimvo**
## Describe your changes
Used telemetry.log_api functionality to generate logs for Jupysql

### Example:

Cell:
```
top_artist = %sql --with top_artist SELECT * FROM top_artist
top_artist.bar()
```
These 2 lines will generate two separate `jupysql-success` logs, one for executing the query and one for the plotting.
```
        "metadata": {
            "action": "execute",
            "query": "WITH genres_fav AS (\n    \nSELECT * FROM Genre\nWHERE Name\nLIKE '%rock%'\nOR Name LIKE '%metal%' \n\n), tracks_with_info AS (\n    \nSELECT t.*, a.title AS album, ar.Name as artist\nFROM Track t\nJOIN Album a\nUSING (AlbumId)\nJOIN Artist ar\nUSING (ArtistId)\n\n), track_fav AS (\n    \nSELECT t.*\nFROM tracks_with_info t\nJOIN genres_fav\nON t.GenreId = genres_fav.GenreId\n\n), top_artist AS (\n    \nSELECT artist, COUNT(*) FROM track_fav\nGROUP BY artist\nORDER BY COUNT(*) DESC\n\n)\nSELECT * FROM top_artist\n",
            "args": {
                "line": [
                    "SELECT",
                    "*",
                    "FROM",
                    "top_artist"
                ],
                "connections": false,
                "close": null,
                "creator": null,
                "section": null,
                "persist": false,
                "no_index": false,
                "append": false,
                "connection_arguments": {},
                "file": null,
                "save": null,
                "with_": [
                    "top_artist"
                ],
                "no_execute": false
            },
            "result": {
                "artist": [
                    "Iron Maiden",
                    "Led Zeppelin",
                    "U2"
                ],
                "COUNT(*)": [
                    204,
                    114,
                    112
                ]
            }
        }
```
```
        "metadata": {
            "action": "bar",
            "key_word_sep": " ",
            "title": null
        }
```

### Queries
Run queries and filter out successful jupysql events by the event name: `jupysql-success`
Break events by actions (i.e: 'plot', 'bar', 'pie', 'execute', etc...)

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [] I have added thorough tests (when necessary).
- [] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

### CODE REVIEW

**Comment by idomic** [comment]
@yafimvo @edublancas is this still relevant?
If so, please review, fix conflicts

**Review by edublancas — CHANGES_REQUESTED** [review]
some parameters might contain sensitive information so for now, let's not log any metadata and just the event names

**Comment by idomic** [comment]
@yafimvo let's fix this and push

**Comment by idomic** [comment]
@yafimvo there's still conflicts with main

**Comment by idomic** [comment]
Also, I know there was a change in telemetry, compare with SKE to make sure we're aligned here.

**Comment by yafimvo** [comment]
@idomic in SKE we use `SKLearnEvaluationLogger`. I used here with the existing logger we use in ploomber `@telemetry.log_call`

**Review by idomic — APPROVED** [review]
looking good!

**Comment by Bidek56** [comment]
@idomic How do I turn off the telemetry feature from `jupysql`? thx

**Comment by Bidek56** [comment]
Based on the config above, are collecting the submitted SQL and the query results. 
Not cool and potentially very illegal in many places. :(
Have you heard of EU or CA privacy laws?

**Comment by edublancas** [comment]
we're not logging sql queries and we're not logging query results. just event names. you can check the source code

**Pull request merged**
