### PR TITLE
Experimental - Interactive 

### PR DESCRIPTION
**Pull request by tonykploomber**
## Describe your changes

To combine the ipywidget interactive component into jupysql

This is the demo for first example - integer slider, we want to provide the interactive sql command, so user can have this command parameter, then the `{{VARIABLE}}` can be passed in the user's sql:

`--interact-slider VARIABLE DEFAULT_VALUE`

Example
```
show_limit = 20
body_mass_lower_bound = (0,6000,100)
sex_selection = widgets.RadioButtons(
    options=['MALE', 'FEMALE'],
    description='Sex',
    disabled=False
)
species_selections= widgets.SelectMultiple(
    options=['Adelie', 'Chinstrap', 'Gentoo'],
    value=['Adelie', 'Chinstrap'],
    #rows=10,
    description='Species',
    disabled=False
)
%%sql --interact show_limit --interact body_mass_lower_bound --interact species_selections --interact sex_selection
SELECT * FROM penguins.csv 
WHERE species IN{{species_selections}} AND 
body_mass_g > {{body_mass_lower_bound}} AND 
sex == '{{sex_selection}}'  
LIMIT {{show_limit}} 

```

https://user-images.githubusercontent.com/123580782/226043317-669de18e-c3de-49f5-8e5e-3363b59de4ef.mov

[Doc
](https://binder.ploomber.io/v2/gh/ploomber/jupysql/150-simple-interactive-dashboard-with-jupysql-and-voila?urlpath=lab/tree/doc/user-guide/interactive.md)

## Issue ticket number and link
Closes #x

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added thorough [tests](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#testing) (when necessary).
- [ ] I have added the right documentation in the [docstring](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#documenting-changes-and-new-features) and [changelog](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#changelog) (when needed)

### CODE REVIEW

**Comment by tonykploomber** [comment]
@edublancas  @idomic 
This is the first example of combining the ipywidget widget and our command, the hardest part is to dynamically generate the widget and hookup with our codebase by smartly injecting the variable into local namespace, I would say the possible limitation is performance if the query takes time, since the slider responsive speed seems super fast but the actual query might be slow, lots thing need to see.

Please LMK what you think and what we should focus next

**Review by edublancas — CHANGES_REQUESTED** [review]
looks like the docs building are failing bc they're missing ipywidgets, please add.

the approach you took is interesting since the user doesn't  need to know how ipywidgets work. another use case I'm thinking is to use the same widget to trigger updates in multiple cells.

for example, the widget might define a threshold value and then multiple plots could be updated by subselecting such data, is something like that possible?

**Comment by tonykploomber** [comment]
> @tonykploomber seems like it's still failing the docs so I couldn't test it, please fix it. Looks very cool in the video! ( I also didn't see tests for it, we need to check if there's a way of testing those features). @edublancas to your point, I think it can be super valuable, kind of these reactive cells. I think we should benchmark it to see how slow it is (especially with millions of rows). I also think we should separate it into a different issue to avoid a slowdown on this PR.

1. Testing - Since this will produce the interactive UI, I don't think the current pytest framework has enough ability to cover this. In the ipywidgets, they use Galata framework for [visual regression testing](https://ipywidgets.readthedocs.io/en/stable/dev_testing.html#visual-regression-tests), it's like generating the snapshot and using test reports to validate the finalized UI (manually check 👀), we can have another CI flow to check this...

**Comment by edublancas** [comment]
Alright, so I'm thinking of the minimum useful thing we can build for users.

One typical use case for interactivity is to update a plot based on specific attributes. For example, given the [penguins](https://github.com/mwaskom/seaborn-data/blob/master/penguins.csv) dataset, I might configure a checkbox button to select the species, a radio button for the island and a numeric field for the body_mass. Then, depending on the values I select, the output table will filter them out.

Since we want to give users the flexibility to choose the widget, I think the option should be `--interact some_widget`; while this implies that the user has to code the widget externally I think it's the best option at the moment until get more feedback and figure the final API.

Once we have this, we can make a release and decide what to build further.

**Comment by tonykploomber** [comment]
Good news is I th

> Alright, so I'm thinking of the minimum useful thing we can build for users.
> 
> One typical use case for interactivity is to update query results based on specific attributes. For example, given the [penguins](https://github.com/mwaskom/seaborn-data/blob/master/penguins.csv) dataset, I might configure a checkbox button to select the species, a radio button for the island and a numeric field for the body_mass. Then, depending on the values I select, the output table will filter them out.
> 
> Since we want to give users the flexibility to choose the widget, I think the option should be `--interact some_widget`; while this implies that the user has to code the widget externally I think it's the best option at the moment until get more feedback and figure the final API.
> 
> Once we have this, we can make a release and decide what to build further.

I think this is something doable! Also I have some progress in regards of this:

We can utilize the widget created by the user, by doing this we provide more flexibility about the widget type, behavior,
So user will define different widgets like:
```
show_limit = 20
body_mass_lower_bound = (0,6000,100)
sex_selection = widgets.RadioButtons(
    options=['MALE', 'FEMALE'],
    description='Sex',
    disabled=False
)
species_selections= widgets.SelectMultiple(
    options=['Adelie', 'Chinstrap', 'Gentoo'],
    value=['Adelie', 'Chinstrap'],
    #rows=10,
    description='Species',
    disabled=False
)
```
Then
```
%%sql --interact show_limit --interact body_mass_lower_bound --interact species_selections --interact sex_selection
SELECT * FROM penguins.csv WHERE species IN{{species_selections}} AND body_mass_g > {{body_mass_lower_bound}} AND sex == '{{sex_selection}}'  LIMIT {{show_limit}} 
```
https://user-images.githubusercontent.com/123580782/225975661-72d27944-6a04-471d-a394-7ab5b0d06ee5.mov

I'll create the new doc to present all basic usages, then we can see what's the next step of this

**Comment by tonykploomber** [comment]
@edublancas 

Two things need some discussion:
1. Testing, the Galata framework, we might need to set up the javascript environment for that, I think we better use the similar way as how we did in sklearn-evaluation, since they have same pupose.

But the way we did in sklearn-evaluation is to import:
```
from matplotlib.testing.decorators import image_comparison as _image_comparison
```
Which imports from matplotlib, but probably they are not related here

Do you think is any cleaner way to write the testing here?

2. Document preview, I wrote `doc/user-guide/interactive.md` but it seems not able to successfully show the ipywidget on the jupyter notebook when we are previewing it. This is the topic we discussed earlier that we might need another environment to host this ipywidget demo page. What you think?

This is the preview link: https://jupysql--256.org.readthedocs.build/en/256/user-guide/interactive.html

Red section is the missing part:
Screenshot 2023-03-17 at 5 41 20 PM

**Comment by edublancas** [comment]
testing: I wouldn't worry much about it. Let's just mock the widgets. In our tests we can create a mock a widget and pass it to the magic (I'm guessing you are accessing the widget's state with something like `widget.value`), then see if the values are passed and the output is expected (e.g., only female/male penguins are displayed).

displaying: that's expected, [ipywidgets](https://jupyterbook.org/en/stable/interactive/interactive.html#ipywidgets) do not work in jupyter book, let's just add a banner a button at the top so they can start the binder environment (the rocket button at the top takes them there but it isn't highly visible)

**Comment by tonykploomber** [comment]
The binder preview: https://binder.ploomber.io/v2/gh/ploomber/jupysql/150-simple-interactive-dashboard-with-jupysql-and-voila?urlpath=lab/tree/doc/user-guide/interactive.md

@edublancas Do you have any idea how to let it rebuild? Seems the version still kind of staying on the old commit

**Comment by edublancas** [comment]
> @edublancas Do you have any idea how to let it rebuild? Seems the version still kind of staying on the old commit

binder should re-build the docker image whenever there is a new push. What I do is I grab the link from the documentation preview but something is off here because I cannot even see the unit tests running. (I thought that converting this from draft to PR would trigger but didn't fix it). Try pushing again or open another PR.

**Comment by tonykploomber** [comment]
Preview link is updated, please review

Testing: 
Since we are only sending basic data types or [Widget Instance](https://ipywidgets.readthedocs.io/en/7.x/examples/Widget%20List.html) from user namespace directly into `@interact`, the difficulty I was facing is I couldn't see the out result (the actual sql query result)  from the `out = ip.run_cell("%sql --interact my_variable SELECT * FROM author LIMIT 5")`, I guess it was there is some async delay between the widget creation and the result.

For now I can only test if we are seeing the `Interactive mode, please interact with below widget(s)` from the test case

**Pull request closed without merging**
