### PR TITLE
showing integration guide if connection fails

### LINKED ISSUE #21: validating input parameter when initializing connection
When starting a new session, users can connect to a db like this:

```python
%sql connection_string
```

However, the `connection_string` is not validated, and if I pass an invalid object:

```python
%sql "not a connection string"
```

```python
%sql 100
```

The following message shows:

```
Environment variable $DATABASE_URL not set, and no connect string given.
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])
```

This is confusing as it doesn't tell me my input is wrong. It says "no connection string given", but that's incorrect.

### PR DESCRIPTION
**Pull request by mehtamohit013**
## Describe your changes
- Added check to guess the DB, that the user may try connecting to

## Issue number

Closes #21 

## Checklist before requesting a review

- [ ] Performed a self-review of my code
- [ ] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [ ] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [ ] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

----
:books: Documentation preview :books:: https://jupysql--503.org.readthedocs.build/en/503/

### CODE REVIEW

**Comment by mehtamohit013** [comment]
When a new connection is made

- If the connection string contains `@` or `://`, only then the string is considered as a connection string, else it is converted to an empty string `""`
    - In such a case, I have added another check to see what is the closest DB to the connection string and printed the link to docs

```python
%load_ext sql
%sql postgresql@dsdsafddvdsvdfb
```    
    
```python
UsageError: An error happened while creating the connection: Could not parse SQLAlchemy URL from string 'postgresql@dsdsafddvdsvdfb'.

Perhaps you meant to use the 'postgressql' db 
To find more information regarding connection: https://jupysql.ploomber.io/en/latest/integrations/postgres-connect.html

To fix it:

Pass a valid connection string:
    Example: %sql postgresql://username:password@hostname/dbname

Documentation: https://jupysql.ploomber.io/en/latest/connecting.html
If you need help solving this issue, send us a message: https://ploomber.io/community
 ```
    
- If it doesn't contain the above, then it is considered a SQL command, and the connection string is empty 

@edublancas @idomic 
Any more suggestions?

**Review by edublancas — CHANGES_REQUESTED** [review]
the readthedocs build is failing, we fixed this already in master so please rebase

**Comment by edublancas** [comment]
> If the connection string contains @ or ://, only then the string is considered as a connection string, else it is converted to an empty string ""

I think `@` can lead to false negatives. for example, `duckdb://` is a valid connection string. but I think  `://` is a good heuristic. What you can do is check if  `://` is missing, if so, add to the error message "{string} doesn't look like a valid connection string, ensure it follow the sqlalchemy format)

another useful link is this: https://jupysql.ploomber.io/en/latest/howto.html#connect-to-existing-engine

if people are unable to connect via a connection string, they can use an engine directly

**Review by edublancas — APPROVED** [review]

**Comment by edublancas** [comment]
@mehtamohit013: thanks for pointing me to the parse, I'll open a new issue to tackle some issues we have there

**Pull request merged**
