### PR TITLE
Support for SqlMagic.autopolars

### LINKED ISSUE #138: Feature request: support for SqlMagic.autopolars
Thanks for creating `jupysql`, I've been playing with it for a few days and it's awesome!

Since I've been experimenting with [polars](https://www.pola.rs/) at the same time, I thought it would be useful for jupysql to support `SqlMagic.autopolars`, automatically converting results to polars Dataframes, similar to `SqlMagic.autopandas`.

I've had a quick look at the source code and I *think* this is a relatively small change, I'd be happy to make an attempt if this is something you'd accept (I'd add docs and tests too).

One thing wrt implementation I'm not sure is easy to do is the fact that ideally `SqlMagic.autopolars` and `SqlMagic.autopandas` should be mutually exclusive, i.e. an error should show if you set both to true. I haven't dug deeply into the code though, perhaps that's not too hard either.

### PR DESCRIPTION
**Pull request by jorisroovers**
Allows auto conversation of sql cells to polars Dataframes.

Closes #138

----
:books: Documentation preview :books:: https://jupysql--142.org.readthedocs.build/en/142/

### CODE REVIEW

**Comment by jorisroovers** [comment]
From #138:
> I think when calling autopandas, autopolars should be automatically turned off and vice-versa. we should also display a message letting the user know (i.e., something like "turned autopandas off since autopolars was turned on")

This is still missing from this PR. I looked into this but didn't find the right place to put this. I believe the setting of `autopolars` and `autopandas` are handled using some special under-the-hood logic of `Configurable` (which `SqlMagic` extends from). 

https://github.com/ploomber/jupysql/blob/bf9a19501d6a282ffa6632e14a4af0f97116b063/src/sql/magic.py#L62

As such, I don't think there is a function in which I can put an `if` construct that checks whether either `autopandas` or `autopolars` is set and unset the other one (and print a message).

I think this might be possible using a class property setter for both `autopandas` and `autopolars`, but the implementation of those isn't very clean: https://stackoverflow.com/a/71740701/381010

This is a critical missing piece though, because in the current implementation `autopandas` will always take precedence over `autopolars` which is unexpected if `autopolars` is enabled after `autopandas`.

@edublancas, do you have any suggestions?

And of course, let me know if you have other feedback on the code too :-)

**Comment by edublancas** [comment]
took a quick look at the code, looks good overall! I'll take another look once the missing parts are done.

so for setting the autopandas/autopolars exclusive logic:

IPython magics use the traitlets library, and there's an easy way to set an observer: https://traitlets.readthedocs.io/en/stable/using_traitlets.html

so something like this in magic.py:

```python
from traitlets import observe


@magics_class
class SqlMagic(Magics, Configurable):
    @observe("autopandas")
    def _observe_bar(self, change):
        print(change["old"])
        print(change["new"]) 
```

with this, you can observe changes to autopandas and autopolars.

to switch values, I believe you can do `self.autopandas = True` - let's see if that works

**Comment by jorisroovers** [comment]
Ok, that worked, thanks!

Should be ready for review now :-)

**Comment by edublancas** [comment]
thank a lot! we'll release this shortly!

**Pull request merged**
