### PR TITLE
Autocompletion extension

### PR DESCRIPTION
**Pull request by neelasha23**
## Describe your changes
Autocompleter extension for JupyterLab

## Issue ticket number and link
Closes #x

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added thorough [tests](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#testing) (when necessary).
- [ ] I have added the right documentation in the [docstring](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#documenting-changes-and-new-features) and [changelog](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#changelog) (when needed)

----
:books: Documentation preview :books:: https://jupysql--291.org.readthedocs.build/en/291/

### CODE REVIEW

**Comment by neelasha23** [comment]
I'm a bit blocked here. Need some help in progressing further.

1. First I run the `pkgmt setup` command for creating the dev setup. This doesn't seem to have Jupyterlab by default.
```
(jupysql) neelashasen@192 jupysql % jupyter --version
Selected Jupyter core packages...
IPython          : 8.11.0
ipykernel        : not installed
ipywidgets       : not installed
jupyter_client   : not installed
jupyter_core     : 5.3.0
jupyter_server   : not installed
jupyterlab       : not installed
nbclient         : not installed
nbconvert        : not installed
nbformat         : 5.8.0
notebook         : not installed
qtconsole        : not installed
traitlets        : 5.9.0
```

If I install Jupyter-lab (Version 3.6.2) and run `%load_ext sql` in the notebook it throws error `ModuleNotFoundError: No module named 'sql'`.

2. I'm confused about how to go about adding the autocompletion module in the setup.py file. `autocompletion` folder itself has the `setup.py` and all necessary files to create a Python package. Currently I'm installing it this way manually (development mode). Also this would work only if Jupyterlab is installed in the environment. Don't we need to add `jupyterlab` to the requirements?:
 ```
cd autocompletion 
pip install -ve .
jlpm run build
```

@edublancas

**Comment by edublancas** [comment]
1. Open a notebook in jupyterlab and execute `import sys; print(sys.executable)` - does the printed path match the conda environment generated by `pkgmt setup`? My guess is not, and your jupyterlab is picking up a different environment. Ensure that you're installing and running jupyterlab from the same environment that `pkgmt setup` creates - let me know if you have other issues
2. we'd have to merge their setup.py with ours, my guess is that the setup.py from the example contains a few extra fields; we should copy those. We did something similar in [ploomber](https://github.com/ploomber/ploomber/blob/2a6287f1beea9f51ecbe59ddebac266cef6c77e8/setup.py#L129), as you can see we added `data_files`, which copies the files from our extension
3. I'm unfamiliar with the jupyter plugin architecture, but sounds like you are thinking of doing some more research on this?

**Comment by neelasha23** [comment]
> 2. we'd have to merge their setup.py with ours, my guess is that the setup.py from the example contains a few extra fields; we should copy those. We did something similar in [ploomber](https://github.com/ploomber/ploomber/blob/2a6287f1beea9f51ecbe59ddebac266cef6c77e8/setup.py#L129), as you can see we added `data_files`, which copies the files from our extension

I tried creating a `setup.py` file similar to [this](https://github.com/jupyterlab/extension-examples/blob/master/kernel-messaging/setup.py). Doesn't look like this is installing the package. The package is still being installed from pyproject.toml file. I'm guessing we need to convert the logic in `.toml` file to `setup.py` format and then merge?

> 3. I'm unfamiliar with the jupyter plugin architecture, but sounds like you are thinking of doing some more research on this?

Yes need to understand better how to capture the asynchronous kernel output within the script. 

@edublancas

**Comment by edublancas** [comment]
> I tried creating a setup.py file similar to [this](https://github.com/jupyterlab/extension-examples/blob/master/kernel-messaging/setup.py). Doesn't look like this is installing the package. The package is still being installed from this [pyproject.toml](https://github.com/ploomber/jupysql/blob/08c3d124f2f03649b07ce875504332eadb1e3296/autocompletion/pyproject.toml) file. I'm guessing we need to convert the logic in .toml file to setup.py format and then merge, although I'm not sure if this is relevant for npm ? I'm not much aware of the toml structure so still trying to understand.

yes, some projects have a pyproject.toml instead of a setup.py, so then we need to figure out how to translate that into a setup.py; you can try asking in the jupyter community: https://discourse.jupyter.org/

**Comment by neelasha23** [comment]
Opening a clean PR [here](https://github.com/ploomber/jupysql/pull/323)

**Pull request closed without merging**
