### PR TITLE
Improving parsing logic

### LINKED ISSUE #610: improving `<<` parsing logic
this is related to: https://github.com/ploomber/jupysql/issues/525

this works (spaces in both sides):

```
%sql df << select * from penguins.csv
```

but this doesn't:

```
%sql df<<select * from penguins.csv
%sql df    <<select * from penguins.csv
%sql df    <<    select * from penguins.csv
```

we should also cover the cases where there is a `=`:

```
%sql df=<<select * from penguins.csv
%sql df    =<<select * from penguins.csv
%sql df    =<<    select * from penguins.csv
%sql df=   <<    select * from penguins.csv
```

### PR DESCRIPTION
**Pull request by anupam-tiwari**
## Issue number

Closes #610 

## Checklist before requesting a review

- [x] Performed a self-review of my code
- [x] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [x] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).

----
:books: Documentation preview :books:: https://jupysql--619.org.readthedocs.build/en/619/

### CODE REVIEW

**Comment by tonykploomber** [comment]
Seems CI is failing

**Comment by edublancas** [comment]
please merge from master, the CI has been fixed

**Comment by edublancas** [comment]
@anupam-tiwari any updates?

**Comment by anupam-tiwari** [comment]
test_parse_connect_shovel_over_newlines() test is failing, so I am improving the logic

**Pull request closed without merging**
