### PR TITLE
Upgrade to Oracle Database Free

### PR DESCRIPTION
**Pull request by gvenzl**
## Describe your changes

Hi all,

This PR is a minor change upgrading the Oracle Database docker image from [gvenzl/oracle-xe](https://hub.docker.com/r/gvenzl/oracle-xe) to the successor image [gvenzl/oracle-free](https://hub.docker.com/r/gvenzl/oracle-free).

## Issue number

N/A

## Checklist before requesting a review

- [x] Performed a self-review of my code
- [ ] ~~Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)~~
- [ ] ~~Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).~~
- [x] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

----
:books: Documentation preview :books:: https://jupysql--943.org.readthedocs.build/en/943/

### CODE REVIEW

**Comment by neelasha23** [comment]
The CI is failing. Please add a Doc entry to the changelog and push the changes @gvenzl

**Comment by edublancas** [comment]
@neelasha23 in the meantime, can you run the tutorial to see everything works?

**Comment by neelasha23** [comment]
We need to also modify the service name to `FREEPDB1` at two places in the notebook:

```
engine = create_engine(
    "oracle+oracledb://ploomber_app:ploomber_app_password@localhost:1521/?service_name=FREEPDB1"  # noqa: E501
)
```

and 

```
%sql oracle+oracledb://ploomber_app:ploomber_app_password@localhost:1521/?service_name=FREEPDB1
```
@gvenzl 

Otherwise it works @edublancas

**Comment by gvenzl** [comment]
Hi @edublancas, hi @neelasha23,

Thanks a lot for considering this PR!

I'm sorry that I somehow missed the updated service name and the changelog entry.
I have added both as requested and pushed to this PR again.

Thanks,

**Comment by neelasha23** [comment]
> I'm sorry that I somehow missed the updated service name and the changelog entry. I have added both as requested and pushed to this PR again.

No issues. Looks good now!

**Review by neelasha23 — APPROVED** [review]

**Comment by gvenzl** [comment]
Awesome, great to hear, thanks @neelasha23!

**Comment by edublancas** [comment]
thanks for your contribution, @gvenzl!

**Comment by gvenzl** [comment]
My pleasure! Thanks for merging it! :)

**Pull request merged**
