### PR TITLE
Add access by column

### PR DESCRIPTION
**Pull request by laowantong**
## Describe your changes

The proposed method `ResultSet.column()` iterates on a column given by name.

https://github.com/ploomber/jupysql/blob/17ab97c5307cfb2d8c8fc5cae0c672083cc8f583/src/sql/run/resultset.py#L249-L256

Additions:
- a method `column(name)` in `resultset.py` (above);
- a method `test_resultset_column(result_set)` in `test_resultset.py` with a successful test and a failed test;
- a paragraph in `doc_intro.md`;
- an entry in `changelog.md`.

## Checklist before requesting a review

- [x] Performed a self-review of my code
- [x] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [x] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [x] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

----
📚 Documentation preview 📚: https://jupysql--1002.org.readthedocs.build/en/1002/

### CODE REVIEW

**Comment by neelasha23** [comment]
@laowantong Hey is there a related issue? Please mention the issue number also

**Comment by laowantong** [comment]
No existing issue. I have just tried to add a feature which I felt was missing for my usage. Not sure why some checks fail. Feel free to close this PR is the procedure is not OK or you think the feature is useless.

**Comment by neelasha23** [comment]
> No existing issue. I have just tried to add a feature which I felt was missing for my usage. Not sure why some checks fail. Feel free to close this PR is the procedure is not OK or you think the feature is useless.

Sure will have a look. There are lint issues in the changes. Please refer to [contributing guidelines](https://ploomber-contributing.readthedocs.io/en/latest/contributing/submitting-pr.html?highlight=lint#linting-formatting)
Also, do include a description of the changes in the PR description @laowantong

**Comment by laowantong** [comment]
Sorry for spamming you with my failed attempts to make the checks pass. There are still lint issues, although pkgfmt succeeds on my machine:

```
$ pkgmt format
Running command:black .
All done! ✨ 🍰 ✨
115 files left unchanged.
Running command:nbqa black .
All done! ✨ 🍰 ✨
56 files left unchanged.
Finished formatting with black!
```

**Comment by neelasha23** [comment]
> Sorry for spamming you with my failed attempts to make the checks pass. There are still lint issues, although pkgfmt succeeds on my machine:
> 

The lints are passing but the testcase `test_resultset_column` is failing. @laowantong

**Comment by laowantong** [comment]
Too much friction for me, sorry. I cannot run the tests on my machine. There are multiple failures everywhere. I give up. You can close this PR. Thanks.

**Pull request closed without merging**
