### PR TITLE
Twice message printing when switching to the current connection

### LINKED ISSUE #772: message is printed twice when switching to the current connection
if moving to the current connection, the message should not appear again: https://github.com/ploomber/jupysql/pull/768#issuecomment-1657862164

### PR DESCRIPTION
**Pull request by anupam-tiwari**
## Issue number

Closes #772 

## Checklist before requesting a review

- [x] Performed a self-review of my code
- [x] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [x] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).

----
:books: Documentation preview :books:: https://jupysql--773.org.readthedocs.build/en/773/

### CODE REVIEW

**Comment by anupam-tiwari** [comment]
@edublancas @neelasha23 does this look good?

**Comment by edublancas** [comment]
@anupam-tiwari yes, there is still a bug. if a user tries to switch to the same connection, the message should not appear. if you try to switch to a different one, it should.

**Comment by anupam-tiwari** [comment]
looking into it!

**Comment by edublancas** [comment]
@anupam-tiwari please avoid closing PRs, especially when there are reviews already as this loses the context from existing reviews.

**Comment by anupam-tiwari** [comment]
> @anupam-tiwari please avoid closing PRs, especially when there are reviews already as this loses the context from existing reviews.

so sorry about that, I messed up my local repo so had to delete it, will keep in mind!

**Pull request closed without merging**
