### PR TITLE
540 add padding to explorer

### LINKED ISSUE #540: add padding to table explorer
the buttons in the table explorer (https://github.com/ploomber/jupysql/pull/420) are hidden by the horizontal scrollbar, making it difficult to click, we need to add some padding:

Screenshot 2023-05-29 at 2 57 52 p m

### PR DESCRIPTION
**Pull request by AnirudhVIyer**
## Describe your changes
Added bottom-padding to the div containing Prev/Next buttons. Now they won't be hidden by the horizontal scroll bar
## Issue number

Closes #540

## Checklist before requesting a review

- [x] Performed a self-review of my code
- [x] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [x] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [x] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

----
:books: Documentation preview :books:: https://jupysql--589.org.readthedocs.build/en/589/

### CODE REVIEW

**Comment by AnirudhVIyer** [comment]
@edublancas  I have added the padding and checked the implementation on binder. 
It works. 

ps: when i try to run the table-explorer locally it loads the table but the buttons are unresponsive. 
Any idea why it might be so?

**Comment by edublancas** [comment]
> ps: when i try to run the table-explorer locally it loads the table but the buttons are unresponsive.
Any idea why it might be so?

maybe you're missing jupysql-plugin? `pip install jupysql-plugin`, let me know if that fixes it, otherwise please open an issue!

**Comment by AnirudhVIyer** [comment]
> > ps: when i try to run the table-explorer locally it loads the table but the buttons are unresponsive.
> > Any idea why it might be so?
> 
> maybe you're missing jupysql-plugin? `pip install jupysql-plugin`, let me know if that fixes it, otherwise please open an issue!

It fixes it. Working now! Thank you!

**Comment by edublancas** [comment]
can you try this? let's ensure there isn't any bug.

in a new conda environment, install jupysql, then try running the explorer. you should get an error asking you to install jupysql-plugin

**Pull request merged**
