### PR TITLE
fix sqlalchemy2 compatibility

### LINKED ISSUE #234: fix sqlalchemy 2 compatibility
we released a new version over the weekend with the compatibility with sqlalchemy 2; however, some users reported errors.

When investigating it, I realized that even though we removed the `sqlalchemy<2`; pip was still installing sqlalchemy 1.4 in the CI (most likely due to some extra dependency). Hence, the CI was only testing 1.4.

seems like the issue is easy to fix and we just need to ensure that in sqlalchemy 2, we run the execute method like this:

```python
conn.session.execute(sqlalchemy.sql.text("select * from table"))
```

instead of this

```python
conn.session.execute("select * from table")
```

### PR DESCRIPTION
**Pull request by Palashio**
## Describe your changes

Fixes sqlalchemy2 compatibility. Changes all places where .execute is called through sqlalchemy to new version.

## Issue ticket number and link
Closes #234 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added thorough [tests](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#testing) (when necessary).
- [ ] I have added the right documentation in the [docstring](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#documenting-changes-and-new-features) and [changelog](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#changelog) (when needed)

----
:books: Documentation preview :books:: https://jupysql--269.org.readthedocs.build/en/269/

### CODE REVIEW

**Review by edublancas — CHANGES_REQUESTED** [review]
I took a look at the code and fixed some errors but realized this PR still needs some work:

- the CHANGELOG was reformatted (possibly some IDE misconfiguration)
- fixed some tests, but others are failing now - i think the best way is to debug locally using pdb https://docs.pytest.org/en/7.1.x/how-to/failures.html

The main problem I encountered is that we have multiple types of db connections: sqlalchemy, native drivers and our sql.Connection, when passing SQL queries, we might be mixing them one another (e.g., passing sqlalchemy.text to a native driver connection breaks)

**Comment by edublancas** [comment]
another tool I use for debugging is `from IPython import embed; embed()` - place that right before the test fails so you can explore the values of existing variables interactively

**Comment by tonykploomber** [comment]
> I took a look at the code and fixed some errors but realized this PR still needs some work:
> 
> * the CHANGELOG was reformatted (possibly some IDE misconfiguration)
> * fixed some tests, but others are failing now - i think the best way is to debug locally using pdb https://docs.pytest.org/en/7.1.x/how-to/failures.html
> 
> The main problem I encountered is that we have multiple types of db connections: sqlalchemy, native drivers and our sql.Connection, when passing SQL queries, we might be mixing them one another (e.g., passing sqlalchemy.text to a native driver connection breaks)

Probably I missed why now we have multiple types of DB connections? Since the duckdb connection here should be connected by SQLAlchemy at least (which should be?)

**Comment by edublancas** [comment]
any updates here? @Palashio

**Comment by Palashio** [comment]
Been doing some debugging but still working on that.

**Comment by tonykploomber** [comment]
I'll continue the work

**Pull request closed without merging**
