### PR TITLE
Fixed CI (Doc checking)

### LINKED ISSUE #661: tasks triggered when only modifying changelog and doc/
I realized that unit tests are triggered even though I only modified doc/ and CHANGELOG.md: https://github.com/ploomber/jupysql/pull/660

my understanding is that if my PR only modifies the CHANGELOG.md or files within doc/ tests should not run

image

seem like this line (https://github.com/ploomber/jupysql/blob/aa360f9505c7b0e3ad8968cf38b2ccfc9df9d4a1/.github/workflows/ci.yaml#L77) which appears in a few places is not correctly getting the exit code from the step that determines if only doc/ or changelog.md have been modified

### PR DESCRIPTION
**Pull request by mehtamohit013**
## Describe your changes
Correct Syntax: `-e doc CHANGELOG.md`

## Issue number

Closes #661 

## Checklist before requesting a review

- [x] Performed a self-review of my code
- [x] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [x] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [x] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

----
:books: Documentation preview :books:: https://jupysql--668.org.readthedocs.build/en/668/

### CODE REVIEW

**Comment by mehtamohit013** [comment]
I have created a seperate branch `CI` with the changes and then create a new branch `doc_modified` with only `doc` and `CHANGELOG.md` changes here: #667 

Also created a PR in pkgmt with changes: https://github.com/ploomber/pkgmt/pull/61

**Comment by yafimvo** [comment]
@mehtamohit013 do we need to merge the [pkgmt PR](https://github.com/ploomber/pkgmt/pull/61) in order to test it?

Also, I'm not sure I understand this [PR (667) ](https://github.com/ploomber/jupysql/pull/667). If we changed only docs and/or changelog - No other test should run, right? 

according to [this summary](https://github.com/ploomber/jupysql/actions/runs/5378060411), it looks like the CI tests will run even when we changed only docs/changelog.

image

If it's possible, I think we should test it as follows
1. Create a new commit - change something in the changelog -> CI tests shouldn't run
2. Create a new commit - change something in one of the docs -> CI tests shouldn't run
3. Case 1 and 2 -> CI tests shouldn't run
4. Create a new commit - change something in the code -> CI test should run
5. empty commit

I think we can test all these cases in this PR by modifying the relevant files each time.

**Comment by mehtamohit013** [comment]
Hi @yafimvo,
I believe I have tested the same [here](https://github.com/ploomber/pkgmt/pull/49#issuecomment-1576797242), in this [PR](https://github.com/ploomber/pkgmt/pull/49), and it has been successfully merged.

This PR mainly corrects the syntax, which I added earlier: https://github.com/ploomber/jupysql/pull/626

**Comment by mehtamohit013** [comment]
> Also created a PR in pkgmt with changes: https://github.com/ploomber/pkgmt/pull/61

Also, I have corrected a docstring here, changed no code or logic

**Review by edublancas — APPROVED** [review]

**Pull request merged**
