### PR TITLE
trinodb integration guide first review 

### LINKED ISSUE #436: Trino DB integration guide
We need to add a guide on how to connect to trino and visualize it.

### PR DESCRIPTION
**Pull request by TegveerG**
## Describe your changes

Added .ipynb notebook for Trino DB integration guide. Kept template similar to PostgreSQL guide, but due to different functionality in JupySQL, had to resort to some changes. For eg, `%sqlplot` magic command is not supporting `--schema` option, so specified schema in query itself. Other current issues include not being able to write entire pandas dataframe to Trino for which I have linked Trino's query length configuration properties documentation.

## Issue number

Closes #436 

## Checklist before requesting a review

- [x] Performed a self-review of my code
- [x] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [x] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [x] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

----
:books: Documentation preview :books:: https://jupysql--516.org.readthedocs.build/en/516/

### CODE REVIEW

**Review by edublancas — CHANGES_REQUESTED** [review]
for plotting, what if you pass `--table schema.table_name`, does it work?

**Comment by edublancas** [comment]
the linting of your notebook is failing, please fix. more info here: https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html?highlight=linting#linting-formatting

**Comment by TegveerG** [comment]
Hi @edublancas, I reconfigured my conda env with the contribution guidelines and the tests passed. However, the [Read the Docs build](https://readthedocs.org/projects/jupysql/builds/20820934/) fails due to the docker run line:
`docker run -p 8080:8080 --name trino -d trinodb/trino'
Is this because we use the bash magic command?

**Comment by edublancas** [comment]
@TegveerG: ah, yes I forgot about that detail

readthedocs cannot run docker commands, so you need to run it locally, and then tell readthedocs not to run it: https://github.com/ploomber/jupysql/blob/b0c30bf1020a73c0a30d9362c598d99d7ac5a0fe/doc/conf.py#L18

**Review by TegveerG — COMMENTED** [review]
Please review final commit, thank you!

**Comment by TegveerG** [comment]
> for plotting, what if you pass `--table schema.table_name`, does it work?

I had tried that and it does not work, I get the following error:
```sh
ProgrammingError: (trino.exceptions.TrinoUserError) TrinoUserError(type=USER_ERROR, name=MISSING_SCHEMA_NAME, message="line 1:56: Schema must be specified when session schema is not set", query_id=20230525_205041_00042_qp4h2)
[SQL: SELECT MIN("trip_distance"), MAX("trip_distance") FROM "default.taxi"]
```

**Review by edublancas — CHANGES_REQUESTED** [review]
fix readthedocs build

**Review by edublancas — APPROVED** [review]

**Pull request merged**
