### PR TITLE
Upload test artifacts

### LINKED ISSUE #543: uploading failed reference images as artifacts
some of our tests produce images and they're compared against a baseline one. when the tests fail, it's difficult to debug failing tests because we don't have access to the images.

we can modify our CI workflow so it uploads the images if the tests fail: https://github.com/actions/upload-artifact

### PR DESCRIPTION
**Pull request by neelasha23**
## Describe your changes
Uploading failed test images

## Issue number

Closes #543 

## Checklist before requesting a review

- [ ] Performed a self-review of my code
- [ ] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)
- [ ] Added [tests](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing) (when necessary).
- [ ] Added [docstring](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features) documentation and update the [changelog](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#changelog) (when needed)

----
:books: Documentation preview :books:: https://jupysql--607.org.readthedocs.build/en/607/

### CODE REVIEW

**Comment by neelasha23** [comment]
Do we want these 2 images per test : test image generated + `*-failed-diff.png`, or the entire content of `result_images`?
@edublancas

**Comment by edublancas** [comment]
> Do we want these 2 images per test : test image generated + *-failed-diff.png, or the entire content of result_images?

what's the difference? if we go with option 1 (test image generated + *-failed-diff.png), what images/data are we *not* uploading?

**Comment by neelasha23** [comment]
> what's the difference? if we go with option 1 (test image generated + *-failed-diff.png), what images/data are we _not_ uploading?

The baseline images are also contained in the folder. 
@edublancas

**Comment by edublancas** [comment]
can you merge from master? the mariadb issue has been fixed

**Comment by neelasha23** [comment]
> can you merge from master? the mariadb issue has been fixed

Done.

@edublancas

**Review by edublancas — APPROVED** [review]

**Pull request merged**
